version: '3.8'
services:
  fe-app:
    image: fe-container:first
    ports:
      - 80:80
    depends_on:
      - nest-app
    networks:
      - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3005:3005
    networks:
      - common-network
  mysql-container:
    image: mysql
    ports:
    - "3308:3306"
    volumes:
      - ${mysql_volume_path}:/var/lib/mysql
    # env_file:
    #   - ./src/.env
    environment:
      MYSQL_DATABASE: ${mysql_server_database}
      MYSQL_ROOT_PASSWORD: ${mysql_server_password}
    restart: always
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - ${redis_volume_path}:/data
    restart: always
    networks:
      - common-network
  minio-container:
    image: bitnami/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ${minio_volume_path}:/bitnami/minio/data
    environment:
      MINIO_ROOT_USER: ${minio_root_user}
      MINIO_ROOT_PASSWORD: ${minio_root_password}
    restart: always
    networks:
      - common-network
    user: "0:0"  # 以 root 用户和组运行

networks:
  common-network:
    driver: bridge
