version: '3.8'
services:
  fe-app:
    image: fe-container:first
    ports:
      - 80:80
    depends_on:
      - nest-app
    networks:
      - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    # ports:
    #   - 3005:3005
    networks:
      - common-network
  mysql-container:
    image: mysql
    ports:
    - "3308:3306"
    volumes:
      - /Users/wuyuliang/mysql-data:/var/lib/mysql
    env_file:
      - ./src/.env
    environment:
      MYSQL_DATABASE: ${mysql_server_database}
      MYSQL_ROOT_PASSWORD: ${mysql_server_database}
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/wuyuliang/redis-data:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
